### ISSUE TITLE
Update to Bevy 0.12

### ISSUE THREAD

**Issue by janhohenheim** [EmiOnGit/warbler_grass#72]
Do you need some help with this? :)

**Comment by EmiOnGit** [comment]
Heyho,
Thanks for reminding me! 

I actually haven't had much motivation to work on this project, especially since I lacked any feedback.
The update to 0.12 opens up a lot of possible simplifications and rewrites since many important parts of the rendering pipeline were changed. 
I think I'll update the project to 0.12 first without rewriting any major logic in the next days!

I also saw a couple of people forking this project in an attempt to update the project to 0.12 but seems like no one got very far. 
However if someone else wants to try their luck feel free to do so.

Have a great day and thanks for the reminder (and motivation boost) :)

**Comment by janhohenheim** [comment]
Hehe, well my feedback is that I love love looove the way your crate looks and would like to continue using it for a long time :)

**Comment by janhohenheim** [comment]
I gave you collaborator rights to Foxtrot so you can patch it in whenever you want even when I'm too busy to review 😄

**Comment by czettnersandor** [comment]
I'm new to Bevy, currently learning Rust along with it, and I was very happy to find a working grass plugin. Then, it suddenly stopped working with the 0.12 upgrade. I did not check why until now. I hope some day I'll be able to contribute, but currently, I'm relying on it will just work after a while. So your work here is much appreciated, even if we don't comment :)

**Comment by EmiOnGit** [comment]
Thanks everybody for your support :) 
The new release is out!
