### ISSUE TITLE
Make the aabb config option not scale the bundle so i have easier control of scale 

### ISSUE THREAD

**Issue by ethereumdegen** [EmiOnGit/warbler_grass#82]
## What problem does this solve or what need does it fill?
Make the aabb config option not scale the bundle so i have easier control of scale

**Comment by ethereumdegen** [comment]
I believe the fix is to remove the last element from this equation

   // ---Y_POSITIONS---
    position_field_offset.y = texture2d_offset(y_texture, position_field_offset.).r * aabb.vect.y;

**Comment by EmiOnGit** [comment]
Is this not relevant anymore? @ethereumdegen

**Comment by ethereumdegen** [comment]
I tried that simple fix and it didnt pan out.  I think it is OK to keep it as is for now .   There are bigger fish to fry.  I actually got this crate working with my setup (besides the crash race cond issue i posted )   check this out 

![image](https://github.com/EmiOnGit/warbler_grass/assets/6249263/9b3d991a-9a00-4086-806a-d164284b1926)

**Comment by EmiOnGit** [comment]
Well first of, this looks great! :) 
The debug aabb is from the grass entity? I actually don't think that the crate should use the aabb at all for scaling purposes. 
A `Plane` should be way better to describe the area since the height of the blades is handled by the height component anyway. Sadly, there is no finite plane in bevy (was added recently). I'll swap out the aabb in the new mayor Bevy upgrade
