### ISSUE TITLE
Add config options to be able to flip the y_map in x or y direction 

### ISSUE THREAD

**Issue by ethereumdegen** [EmiOnGit/warbler_grass#83]
Add config options to be able to flip the y_map in x or y direction

**Comment by ethereumdegen** [comment]
this would be very useful for me for linking this with my terrain height data

**Comment by ethereumdegen** [comment]
Tldr i was able to get this crate hooked up to my terrain by feeding the terrain height maps in however i had to make z be x and x be z in the shader for the y map input.   So i had to fork this repo

**Comment by ethereumdegen** [comment]
Maybe we can add a config option “transpose y map”

**Comment by EmiOnGit** [comment]
Expected behavior should be that the y-map, normal map and density map are aligned.
A setting to configure transposition/rotation of the y map could lead to weird bugs as the other maps are not aligned anymore.
How about a setting which controls all maps? Couldn't you just make the grass entity a child entity and rotate the transform at 90 degree?
